import pygame

TURTLE_AMOUNT = 4
ARRAY_SIZE = 21

EMPTY = 'EMPTY'
BAG = 'BAG'
CAN = 'CAN'
BOTTLE = 'BOTTLE'
TRASH_LIST = [EMPTY, BAG, CAN, BOTTLE]

# TURTLE BOT
START_X = 10

STEP = 1
UP = 'UP'
DOWN = 'DOWN'
LEFT = 'LEFT'
RIGHT = 'RIGHT'

#screen:
FPS = 60
WINDOW_WIDTH, WINDOW_HEIGHT = 420, 400
WINDOW = pygame.display.set_mode((WINDOW_WIDTH, WINDOW_HEIGHT))